[package]
name = "package-info-rs"
version = "0.1.0"
authors = ["Federico Dolce <psykopear@gmail.com>"]
edition = "2018"

[dependencies]
neovim-lib = "0.6.1"
reqwest = "0.9.15"
semver = "0.9.0"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
